### ISSUE TITLE
[CSS sprite icons] Check if mask size can be simplified

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/material-icons-extended#74]
Currently, the default styles for the CSS sprite apply the following mask size:
```css
.imx-icon {
  -webkit-mask-size: auto var(--size);
}
```
While I can resize with just `--size` conveniently, there are some integrations that still shift width/height only (think igx-button > igx-icon) and in those cases the size of the icon is overridden, but the mask image isn't reacting.
There seem to be a few moving parts, some of which are beyond me, however it does seem like the explicit height might not be needed? With:
```
  -webkit-mask-size: auto;
```
or not setting it all, the icon seems to scale correctly to width/height manipulation (attached sample). Might be very narrow to our current SVG-s, but I think the viewport translates to those having a proportion and with `auto` I believe fall into the second part of the "If the mask-size is auto or auto auto" case of https://developer.mozilla.org/en-US/docs/Web/CSS/mask-size#values
> If it has no dimensions but has a proportion, it's rendered as if contain had been specified instead. 

Where `contain` scales as much while maintaining the aspect. Might even be the value we should be using? Anyway, though it might be worth a check since we can drop one property, can still keep the CSS var but also allow flexible sizing.

Can also try on the MDN example like:
```css
.masked {
  -webkit-mask-image: var(--icon);
  -webkit-mask-size: auto;
  -webkit-mask-repeat: no-repeat;
  width: 150px;
  height: 150px;
  --icon: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" aria-labelledby="poop-title poop-desc" viewBox="0 0 24 24"><path d="M19.5 17h-2a2.5 2.5 0 0 0 0-5h-2a2.5 2.5 0 0 0 0-5h-.684A2.962 2.962 0 0 0 15 6a3 3 0 0 0-3-3 2.97 2.97 0 0 0-1.47.4 2.946 2.946 0 0 1-.316 3.6H8.5a2.5 2.5 0 0 0 0 5h-2a2.5 2.5 0 0 0 0 5h-2a2.5 2.5 0 0 0 0 5h15a2.5 2.5 0 0 0 0-5z"/></svg>');
}
```
This seems to position the svg image quite nicely and responds to with/height changes.

PS: We might opt for an `--icon-size` variable down the line that to allow parent components to specify the size of child icons specifically and have the icon size default to that first, which could also make such integrations smoother.

#### Attachment
[July '23 Test App_angular.zip](https://github.com/IgniteUI/material-icons-extended/files/12173854/July.23.Test.App_angular.zip)
